[package]
name = "contracts"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.10.1"

[dev-dependencies]
snforge_std = "0.42.0"
assert_macros = "2.10.1"

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]
